controller_list:
  - name: "L_xarm7_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - L_joint1
      - L_joint2
      - L_joint3
      - L_joint4
      - L_joint5
      - L_joint6
      - L_joint7
  - name: L_xarm_gripper
    action_ns: gripper_action
    type: GripperCommand
    joints:
     - L_drive_joint
  
  - name: "R_xarm7_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - R_joint1
      - R_joint2
      - R_joint3
      - R_joint4
      - R_joint5
      - R_joint6
      - R_joint7
  - name: R_xarm_gripper
    action_ns: gripper_action
    type: GripperCommand
    joints:
     - R_drive_joint
